name: ACT_LED_LF_POLOLU 

#on:
  #push:
#  pull_request:
#    types:
#      - closed
#    branches:
#      - main

on:
  workflow_call:

jobs:
  setup:
    runs-on: [self-hosted, linux, lf-act-ast]
    #Strategy makes sense if there are multiple versions to test
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v5
        with:
          clean: true
          fetch-depth: 0
          submodules: recursive
      - name: Unshallow Modules
        run: |
          git submodule foreach '
            echo "Fixing submodule $name"
            git fetch --unshallow || git fetch --all
            '
      - name: Nix Setup
        id: nix
        working-directory: ${{ github.workspace }}/lf-3pi-template
        run: |
          nix develop --command true
      - name: Debug git state
        if: steps.nix.outcome == 'failure'
        working-directory: ${{ github.workspace }}/lf-3pi-template
        run: |
          git rev-parse --is-shallow-repository
          git rev-list --count HEAD

  pythonpackages:
    runs-on: [self-hosted, linux, lf-act-ast]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: |
          echo "Push detected"
          echo "$GITHUB_WORKSPACE"
          python3 -m pip install --upgrade pip
          pip3 install opencv-python numpy pandas matplotlib
          python3 -c "import sys; print(sys.version)"
  
  filecleanup:
    runs-on: [self-hosted, linux, lf-act-ast]
    needs: setup
    if: always()
    steps:
      - uses: actions/checkout@v5
      - name: Copy Script
        run: cp $GITHUB_WORKSPACE/test_lf_programs/*.sh $GITHUB_WORKSPACE/lf-3pi-template/
      - name: Run Script
        working-directory: ${{ github.workspace }}/lf-3pi-template/
        run: |
          chmod +x cleanup.sh
          ./cleanup.sh

  filesetup:
    #if: github.event.workflow_run.conclusion == 'success'
    runs-on: [self-hosted, linux, lf-act-ast]
    needs: filecleanup
    steps:
      - name: Copy Files
        working-directory: ${{ github.workspace }}
        run: |
          #ls && ls src/
          cp $GITHUB_WORKSPACE/test_lf_programs/*.py $GITHUB_WORKSPACE/lf-3pi-template
          cp $GITHUB_WORKSPACE/test_lf_programs/*.lf $GITHUB_WORKSPACE/lf-3pi-template/src 
 
  compileblink1:
    runs-on: [self-hosted, linux, lf-act-ast]
    needs: [filesetup]
    steps:
      - name: Compile Blink - 1
        working-directory: ${{ github.workspace }}/lf-3pi-template
        run: nix develop --command lfc src/Blink_1.lf
  
  flashblink1:
    runs-on: [self-hosted, linux, lf-act-ast]
    needs: [compileblink1]
    steps:
    - name: Flashing Blink
      working-directory: ${{ github.workspace }}/lf-3pi-template
      run: nix develop --command picotool load -x bin/Blink_1.elf -f
  
  runblink1:
    runs-on: [self-hosted, linux, lf-act-ast]
    needs: [flashblink1]
    steps:
      - name: Run Test
        id: test1
        working-directory: ${{ github.workspace }}/lf-3pi-template
        run: python3 test_led_module.py 1
  
  compileblink2:
    runs-on: [self-hosted, linux, lf-act-ast]
    needs: [filesetup]
    steps:
      - name: Compile Blink - 2
        working-directory: ${{ github.workspace }}/lf-3pi-template
        run: nix develop --command lfc src/Blink_2.lf
  
  flashblink2:
    runs-on: [self-hosted, linux, lf-act-ast]
    needs: [compileblink2, runblink1]
    steps:
    - name: Flashing Blink
      working-directory: ${{ github.workspace }}/lf-3pi-template
      run: nix develop --command picotool load -x bin/Blink_2.elf -f
  
  runblink2:
    runs-on: [self-hosted, linux, lf-act-ast]
    needs: [flashblink2]
    steps:
      - name: Run Test
        id: test2
        working-directory: ${{ github.workspace }}/lf-3pi-template
        run: python3 test_led_module.py 2

  compileblink3:
    runs-on: [self-hosted, linux, lf-act-ast]
    needs: [filesetup]
    steps:
      - name: Compile Blink - 3
        working-directory: ${{ github.workspace }}/lf-3pi-template
        run: nix develop --command lfc src/Blink_3.lf
  
  flashblink3:
    runs-on: [self-hosted, linux, lf-act-ast]
    needs: [compileblink3, runblink2]
    steps:
    - name: Flashing Blink
      working-directory: ${{ github.workspace }}/lf-3pi-template
      run: nix develop --command picotool load -x bin/Blink_3.elf -f

  runblink3:
    runs-on: [self-hosted, linux, lf-act-ast]
    needs: [flashblink3]
    steps:
      - name: Run Test
        id: test3
        working-directory: ${{ github.workspace }}/lf-3pi-template
        run: python3 test_led_module.py 3
  
  plotgraph:
    runs-on: [self-hosted, linux, lf-act-ast]
    needs: [runblink1, runblink2, runblink3]
    if: |
      needs.runblink1.result == 'success' ||
      needs.runblink2.result == 'success' ||
      needs.runblink3.result == 'success'
    steps:
      - name: Run Test
        working-directory: ${{ github.workspace }}/lf-3pi-template
        run: python3 plot_led.py
       
  blinkreportupload:
    runs-on: [self-hosted, linux, lf-act-ast]
    needs: [plotgraph]
    steps:
      - name: Upload test reports
        working-directory: ${{ github.workspace }}
        run: |
          ls
      - uses: actions/upload-artifact@v4
        with:
          name: Blink-test-report
          path: |
            ${{ github.workspace }}/lf-3pi-template/time_vs_deviation_percent.svg
            ${{ github.workspace }}/lf-3pi-template/blink_results.csv